; Auto-generated. Do not edit!


(cl:in-package action_demo-msg)


;//! \htmlinclude ActionDemoResult.msg.html

(cl:defclass <ActionDemoResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass ActionDemoResult (<ActionDemoResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionDemoResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionDemoResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_demo-msg:<ActionDemoResult> is deprecated: use action_demo-msg:ActionDemoResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <ActionDemoResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_demo-msg:result-val is deprecated.  Use action_demo-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionDemoResult>) ostream)
  "Serializes a message object of type '<ActionDemoResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionDemoResult>) istream)
  "Deserializes a message object of type '<ActionDemoResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionDemoResult>)))
  "Returns string type for a message object of type '<ActionDemoResult>"
  "action_demo/ActionDemoResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionDemoResult)))
  "Returns string type for a message object of type 'ActionDemoResult"
  "action_demo/ActionDemoResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionDemoResult>)))
  "Returns md5sum for a message object of type '<ActionDemoResult>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionDemoResult)))
  "Returns md5sum for a message object of type 'ActionDemoResult"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionDemoResult>)))
  "Returns full string definition for message of type '<ActionDemoResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionDemoResult)))
  "Returns full string definition for message of type 'ActionDemoResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionDemoResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionDemoResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionDemoResult
    (cl:cons ':result (result msg))
))
